### ISSUE TITLE
Connect4 board has 6 rows, not 7

### ISSUE THREAD

**Issue by JonZarate** [kevinAlbs/Connect4#3]
I noticed this API uses a 7x7 matrix, but it should be 6x7 instead.

Searching `Connect4` on Google will show board images and the Wikipedia definition proving it. 

> _Connect Four is a two-player connection game in which the players first choose a color and then take turns dropping colored discs from the top into a seven-column,_ **six-row** _vertically suspended grid._

**Comment by kevinAlbs** [comment]
Thank you for the report. As of https://github.com/kevinAlbs/Connect4/commit/0aff1237c7326c9e7c2c75426e062e41713d57e1 a 6x7 board is supported and is used in [the demo](https://kevinalbs.com/connect4/).

For backwards compatibility, [the API](https://kevinalbs.com/connect4/back-end/info.html) continues to support the 7x7 board.
